/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import funcoes.Funcoes;
import funcoes.CaixaDeDialogo;

/**
 *
 * @author yuri.schmitz
 */
public class telaPrincipal extends javax.swing.JFrame {

    Pessoa pessoa1;
    Pessoa pessoa2;
    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        
        pessoa1 = new Pessoa();
        pessoa2 = new Pessoa();
        
        pessoa1.setCodigo(1);
        pessoa1.setNome("Juca");
        pessoa1.setValorConta(1000);
        pessoa1.setChequeEspecial(200);
        
        pessoa2.setCodigo(2);
        pessoa2.setNome("João");
        pessoa2.setValorConta(1000);
        pessoa2.setChequeEspecial(200);
        
        lblNome1.setText(pessoa1.getNome());
        lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
        lblChequeEspecial1.setText(String.valueOf(pessoa1.getChequeEspecial()));
        
        lblNome2.setText(pessoa2.getNome());
        lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
        lblChequeEspecial2.setText(String.valueOf(pessoa2.getChequeEspecial()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransferencia1 = new javax.swing.JButton();
        lblNome1 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblChequeEspecial1 = new javax.swing.JLabel();
        btnTransferencia2 = new javax.swing.JButton();
        lblNome2 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblChequeEspecial2 = new javax.swing.JLabel();
        txtTransferencia1 = new javax.swing.JTextField();
        txtTransferencia2 = new javax.swing.JTextField();
        btnMensagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransferencia1.setText("Transfere");
        btnTransferencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferencia1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblNome1.setText("Nome");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblValor1.setText("Valor Conta");
        getContentPane().add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblChequeEspecial1.setText("Cheque Especial");
        getContentPane().add(lblChequeEspecial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnTransferencia2.setText("Transfere");
        btnTransferencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferencia2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        lblNome2.setText("Nome2");
        getContentPane().add(lblNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        lblValor2.setText("Valor Conta2");
        getContentPane().add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        lblChequeEspecial2.setText("Cheque Especial");
        getContentPane().add(lblChequeEspecial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        txtTransferencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransferencia1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransferencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));
        getContentPane().add(txtTransferencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, -1));

        btnMensagem.setText("Mensagem");
        btnMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        setSize(new java.awt.Dimension(549, 326));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferencia1ActionPerformed
        // TODO add your handling code here:
        try{
            if(Funcoes.validarNumero(txtTransferencia1.getText())){
                double transf = Double.parseDouble(txtTransferencia1.getText());
                if(pessoa1.credito(transf) == true){
                    pessoa2.debito(transf);
                    Funcoes.mostrarMensagem("Sucesso!");
                }
                lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
                lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
                txtTransferencia1.setText("0");
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um valor válido!!!", 'e');
            }
        
        }catch(Exception ex){
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTransferencia1ActionPerformed

    private void btnTransferencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferencia2ActionPerformed
        // TODO add your handling code here:
        if(Funcoes.validarNumero(txtTransferencia2.getText())){
            try{
                double transf = Double.parseDouble(txtTransferencia2.getText());
                if(pessoa2.credito(transf) == true){
                    pessoa1.debito(transf);
                }
                lblValor1.setText(String.valueOf(pessoa1.getValorConta()));
                lblValor2.setText(String.valueOf(pessoa2.getValorConta()));
                txtTransferencia2.setText("0");

            }catch(Exception ex){
                System.out.println("Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnTransferencia2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtTransferencia1.setText("0");
        txtTransferencia2.setText("0");
    }//GEN-LAST:event_formWindowOpened

    private void txtTransferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransferencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransferencia1ActionPerformed

    private void btnMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensagemActionPerformed
        // TODO add your handling code here:
        boolean resposta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Titulo", "Tem certeza?", 'p');
        if(resposta){
            CaixaDeDialogo.obterinstancia().exibirMensagem("RESPONDEU SIM");
        }else{
            CaixaDeDialogo.obterinstancia().exibirMensagem("RESPONDEU NÃO");
        }
    }//GEN-LAST:event_btnMensagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMensagem;
    private javax.swing.JButton btnTransferencia1;
    private javax.swing.JButton btnTransferencia2;
    private javax.swing.JLabel lblChequeEspecial1;
    private javax.swing.JLabel lblChequeEspecial2;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JTextField txtTransferencia1;
    private javax.swing.JTextField txtTransferencia2;
    // End of variables declaration//GEN-END:variables
}
